### ISSUE TITLE
Docker run not producing any output

### ISSUE THREAD

**Issue by kedartripathy** [nahidalam/modnet_docker#1]
Hello,

I am trying to run MODNet using the dockerized version you have provided on my computer, but I don't see any output after the 'docker run' command. There is no error outputted, but it doesn't print the "saved background" statement at the end of the inference.py file.

I ran 'docker ps -a' to view the exited containers but it did not return anything. I also ran 'docker images' to confirm that the docker image ('modnet') was created.

I get the same behavior when running on Ubuntu 20.04.4 LTS. 

![modnet_docker_error](https://user-images.githubusercontent.com/68572844/156376289-d7fd7c25-53ba-4ac6-a58b-f9297277e4f6.jpg)

**Comment by nahidalam** [comment]
Hmm, I see it is working fine on my side
<img width="1519" alt="Screen Shot 2022-03-03 at 11 03 02 AM" src="https://user-images.githubusercontent.com/2341472/156635738-1d177b5e-2d8e-4f7b-81aa-9bcf23f34b9b.png">

I would try below steps
- make sure you have `__init__.py` here https://github.com/nahidalam/modnet_docker/tree/main/src/models/backbones
- Make sure your docker has enough space. Docker images/containers can hog allocated space and time to time you might need to clear up. I generally do system prune https://docs.docker.com/engine/reference/commandline/system_prune/

**Comment by kedartripathy** [comment]
Thank you for the suggestion, I uninstalled an reinstalled docker on my computer and now it looks like the inference.py file did run all the way through. The output I got is attached.

However, I cannot find the the output images and they were not saved in the output path (demo/image_matting/output). Any ideas how I can obtain the outputs? When I ran inference.py on it's own, the images were successfully saved in the correct folder.

![Docker_run](https://user-images.githubusercontent.com/68572844/156667146-065d8401-ae92-404f-a051-7a65d4ef8126.jpg)

**Comment by nahidalam** [comment]
Okay I found the issue.
I did a major restructuring and update in a new branch https://github.com/nahidalam/modnet_docker/tree/container

This is working on my end. I removed the images and tested and saw it is saved. Please test it out and let me know.

**Comment by kedartripathy** [comment]
That worked, thank you!
